### ISSUE TITLE
[🐞] value attribute is remove on SPA navigation

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4616]
### Which component is affected?

Qwik Runtime

### Describe the bug

I've got something like that  :
```jsx
const Slider = component$((props: SliderProps) => {
  return <input type="range" min={props.min} max={props.max} name={props.name} value={props.value}/>
})
```

When I log the input after navigation with :
- anchor: I see the value in the tag (alongside qwik properties).
![anchor navigation](https://github.com/BuilderIO/qwik/assets/8143464/b2be131a-46b9-47e6-818b-698db50fb930)
- Link : I only see type, min, max & name, but something else
![SPA navigation](https://github.com/BuilderIO/qwik/assets/8143464/3024115d-b7ae-4768-93ae-9d05e108c12a)

As you can see the `value` attribute has been removed. This is an issue when I use `form.reset()`.

With the anchor the reset put the initial value
With the Link the reset put the default value (which seems to be 50 for some reason with a range).

### Reproduction

https://qwik-playground.vercel.app/form/

### Steps to reproduce

In the link about you can click "cancel" to trigger the `reset` event.
When you arrive on the page if you click "cancel" the controls will reset to initial value.
When you navigate on the page with links, and click on "cancel" you'll see all controls reset to default value (except some where reset has been overwritten).

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.74 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 1.1.5 => 1.1.5
    @builder.io/qwik-city: 1.1.5 => 1.1.5
    undici: 5.21.0 => 5.21.0
    vite: 4.3.9 => 4.3.9
```

### Additional Information

The qwik.new stackblitz doesn't work anymore for me which makes it hard to provide a minimal example....

**Comment by diecodev** [comment]
Can you please share a repository with the code?

**Comment by GrandSchtroumpf** [comment]
Sure the page of the app above is here :
https://github.com/GrandSchtroumpf/qwik-playground/blob/main/src/routes/form/index.tsx

**Comment by diecodev** [comment]
The problem that I find in your code is that you use the context of the form before, in the Slider component, if to this you add that the Link component does not allow that the current state changes, everything makes sense, because it does not let the context that you previously used in the Slider component mute its state to the one that you are placing now with the Form. I recommend you to use either two separate contexts or if you need 1 global context, then use in your store 2 objects, 1 to handle the context value of the slider and another to handle the context of the form.

P.S. about the link component you can find it in [the link component documentation](https://qwik.builder.io/docs/api/#link).

**Comment by GrandSchtroumpf** [comment]
I'm sorry, I think using the `Range` as an example is not a good way to display the problem. It actually happens to all controls.
Let's let a look at the [Input](https://github.com/GrandSchtroumpf/qwik-playground/blob/main/src/components/ui/form/input/input.tsx#L19). I've updated the code to comment out the context, so we can see it's not an issue with the context. I use the [props.value](https://github.com/GrandSchtroumpf/qwik-playground/blob/main/src/routes/form/index.tsx#L46) instead.

Scenario 1: use anchor navigation
1. Go to https://qwik-playground.vercel.app/form/ 
2. Open console and see that `value` is set on the `input`
3. Click "cancel" the first input remains the same

Scenario 2: use Link navigation
1. Go to https://qwik-playground.vercel.app
2. Click on "form" on the left navigation
3. Open console and see that `value` is **not** set on the `input`
4. Click "cancel" the first input is cleared

**Comment by diecodev** [comment]
@GrandSchtroumpf Sorry for my nonsense answer, I see what you mention and apparently, the Link component has a strange behavior, if you add a console.log in your code in the range component you will see it on the browser and not on the server. I guess it is a bug to be seen by the qwik team as such. Sorry for the inconvenience.

**Comment by gioboa** [comment]
This is still an issue with Qwik v2.
When you use the Link (SPA navigation) there is no value attribute in the HTML of the input.
If you open directly `my-path` page the value attribute is there.

> [!NOTE]
If I use bind:value instead of value, everything is working fine.


FILE: src/routes/index.tsx
```
import { component$ } from '@qwik.dev/core';
import { Link } from '@qwik.dev/router';

export default component$(() => {
  return <Link href='/my-path'>SPA Navigation</Link>
});
```

FILE: src/routes/my-path/index.tsx
```
import { component$ } from "@qwik.dev/core";

export default component$(() => {
  return <Input value="Hello World" />
});

const Input = component$((props: any) => {
  return <input {...props} value={props.value}/>
})
```

Is it the correct behavior? cc @wmertens @Varixo

**Comment by wmertens** [comment]
@diecodev I think this is just CSR vs SSR. On the client, we use JS to set the data and there's no need to change the HTML attributes. It would be extra work with no benefit.

See https://qwik.dev/playground/#f=5VY9C8IwEN39FaEITWkpDioqtIsIDrqIu1OgYl1EBwn5795HmlzFTXHpUkLymrzcXd49UTTz6exT0RSx%2B%2FIQuy%2BNpNB9XVocJ5AvCFNs95vW4EOpdRYgzf3aSoxO07gIysc9SAImcf1MxkAuJg1GN8lGgHkXb219i3eBpuIZ3R2EWyviVIIggNRXeAcelygzt%2B1xvwOQoxP6aScpvZhnZbvt%2BEcXssZ8yRbBx6HoPMCd0LTHgv8guzOurD4VyrTEVSCAkvHsnCgItHPIbaVspO%2FY5kkMbQ4geWYfxYYw%2BiDLWe3fKc9dffAzwUP6csQ4dCU5RB1ZLP%2BiI2v0Thj9X4vICw
