### ISSUE TITLE
[🐞] from create qwik latest, I can't make cloudflare-pages work since 1.2.14

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#5400]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am using Windows, Visual Code, from there create qwik latest, pnpm install, then cloudflare-pages adapter, pnpm build, then start. In local, no problem but when transfer to [github repo](https://github.com/tidiview/worktop-qwikcity), the cloudflare building do not work at all.
The site builds on cloudflare, but once it has build, the [site](https://66751608.worktop-qwikcity.pages.dev/) appears completely blank since 1.2.15, then 1.2.16 and now, 1.2.17.
I thought that other user would report it and that it would be solved, but it seemed that I am the only one to have that problem therefore may be I have a specific problem, so I decided to put it here.

### Reproduction

https://66751608.worktop-qwikcity.pages.dev/

### Steps to reproduce

pnpm create latest, pnpm install, then cloudflare-pages adapter, pnpm build, then start.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
    Memory: 1.75 GB / 7.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.44)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @builder.io/qwik: ^1.2.17 => 1.2.17
    @builder.io/qwik-city: ^1.2.17 => 1.2.17
    undici: ^5.26.0 => 5.27.2
    vite: ^4.4.11 => 4.5.0
```

**Comment by gioboa** [comment]
I bumped up Qwik to 1.2.16 in one project and I had the same problem.
@tidiview Can you bisect the commits to figure out the problematic commit please?
[Here is the guide](https://github.com/BuilderIO/qwik/blob/main/CONTINUOUS_BUILD.md#bisect-for-regression)

fun fact, the Qwik docs site is on Cloudflare and it's working 🤔

**Comment by tidiview** [comment]
I don't understand the differences between qwik, qwik-city, qwik-labs in that case.
I don't have qwik-lab in my project.
So I think you are talking of qwik and qwik-city but...

**Comment by gioboa** [comment]
I deployed one of my "failing with blank page project" with e CloudFlare CLI and it's working fine. 🤔 

```
- build
- cd dist
- CLOUDFLARE_ACCOUNT_ID=XXX npx wrangler pages deploy .
```

@tidiview Can you test these steps too pls?

**Comment by tidiview** [comment]
@gioboa I tried the previous method, but unfortunately got the same result. I reverted to 1.2.14.
For information, I tried to bisect, but couldn't figure out how to.
After several unsuccessful tries...

**Comment by tidiview** [comment]
@gioboa I tried a new project from scratch, just adding cloudflare-pages. Then created a github repo. Then created a new application from the cloudflare dashboard as usual.
At the end, there is non site at all.

**Comment by tidiview** [comment]
@gioboa I finally tried a new project from scratch, just adding cloudflare-pages. Then did your method: build, cd dist, then wrangler login, then `npx wrangler pages deploy .`
Then, it worked!
I still don't understand why the github repo method I used do not worked, but it worked.

**Comment by tidiview** [comment]
@gioboa sorry to bother you multiple times but OK, I think I have a clue now.
I tried `pnpm wrangler pages deploy .`
I got 118 files uploaded instead of 47 with yours.
Then I had the same problem.
I resumed `npx wrangler pages deploy .` then it worked again.
Can't explain anything but I think that a clue for solving it.

**Comment by tidiview** [comment]
@gioboa For the existing repo, I tried both methods [`npx wrangler pages deploy .` or commit thrue github] but couldn't get it work either way.

**Comment by gioboa** [comment]
Can you try to deploy another Cloudflare site with the same codebase please?

**Comment by tidiview** [comment]
I'm afraid I don't understand.
I tried to deploy another Cloudflare site with 1.2.18 from scratch.
It worked with `npx wrangler pages deploy .` I got 47 files uploaded and it worked.
With the github repo method, I have 117 files upload instead of 47, and it do not work.
So I think I already did what you are asking me to do.
If not, precise what you think please.

**Comment by gioboa** [comment]
This PR #5352 generated the problem. I'm going to revert it

**Comment by mpeg** [comment]
hey both, just saw this, very bizarre that it would only fail on the cloud builds, I have been unable to reproduce this – the builds work fine for me no matter where

Any chance I could get the full build logs from one of the blank page builds? As well as the list of files uploaded, please, these are both available in the deployments section of Cloudflare Pages if you click "View details" on a specific deployment

**Comment by tidiview** [comment]
@mpeg 
What would you like to know precisely?
to precise, I use to:
- have a repo on github, first, upgade to new version. Problem from 1.2.14;
- after upgrade, I would do `pnpm build`;
- the `pnpm start`, checking it is working locally. 117 files changed by build command.
- then `commit to main` on github repo. The commit is just `package.json` file.
- automatically, Cloudflare trigger an update from the update of the github repo.
- automated `build` from the new `package.json` file on Clouflare's server is working well.
- but, when trying new site made out of that build, nothing appears: site is blank.
For the 47 files changed method, @gioboa suggested it: from scratch it is working but from the existing project being upgraded, It doesn't.
Hope this help!
